name: Open Distro for Elasticsearch ODBC Driver 0

on: [push, pull_request]

jobs:    
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: get-dependencies
      run: brew unlink unixodbc && brew install curl && brew install cmake && brew install libiodbc
    - name: configure
      run: mkdir build && cd build && cmake ../src && cd ..
    - name: build
      run: cmake --build build
    - name: test
      run: | 
        bash ./run_test_runner.sh
    - name: create-output
      if: always()
      run: |
        mkdir sql-odbc-builds
        cp ./lib64/*.dylib sql-odbc-builds
        cp -r ./bin64/ sql-odbc-builds
        cp ./bin64/*.html sql-odbc-builds
    - name: upload-test-output
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: mac-output
        path: sql-odbc-builds
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build ; cd build ; cmake ..\\src ; cd ..
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: |
        cp .\\libraries\\VisualLeakDetector\\bin64\\*.* .\\bin64\\Release
        cp .\\libraries\\VisualLeakDetector\\lib64\\*.lib .\\lib64\\Release
        .\run_test_runner.bat
    - name: create-output
      if: always()
      run: |
        mkdir sql-odbc-builds
        cp .\\bin64\\Release\\*.* sql-odbc-builds
        cp .\\lib64\\Release\\*.lib sql-odbc-builds
    - name: upload-test-output
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: windows-output
        path: sql-odbc-builds
