name: C/C++ CI

on: [push, pull_request]

jobs:    
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake ../src && cd ..
    - name: Build
      run: cmake --build build
    - name: test
      run: .\run_test_runner.sh
    - name: create-test-output
      run: |
        mkdir -p sql-odbc-builds
        cp ./bin64/*.html sql-odbc-builds
    - name: upload-test-output
      uses: actions/upload-artifact@v1
      with:
        name: sql-odbc-test-output
        path: sql-odbc-builds
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake ../src && cd ..
    - name: Build
      run: cmake --build build
    - name: test
      run: .\run_test_runner.sh
    - name: create-test-output
      run: |
        mkdir -p sql-odbc-builds
        cp ./bin64/*.html sql-odbc-builds
    - name: upload-test-output
      uses: actions/upload-artifact@v1
      with:
        name: sql-odbc-test-output
        path: sql-odbc-builds
